version: '3.8'

services:

  torchserve:
    build:
      context: .
      dockerfile: ts.Dockerfile
      args:
        - no-cache=true  # Equivalent to --no-cache in Docker build
    image: pytorch/torchserve:ezout-vision-latest
    container_name: ezout-vision-ts
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "7070:7070"
      - "7071:7071"
    # volumes:
      # - ./modelstore:/home/model-server/model-store
      # - ./config:/home/model-server/config
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: torchserve --start --ncs --model-store /home/model-server/model-store --ts-config config/config.ts.properties 
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
