version: '3'

services:
  torchserve:
    build:
      context: .
      # Uses one of the dockerfile
      dockerfile: Dockerfile.ts
      args:
        - no-cache=true  # Equivalent to --no-cache in Docker build
    image: pytorch/torchserve:ezout-vision-latest
    container_name: ezout-vision-ts-grafana
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "7070:7070"
      - "7071:7071"
    volumes:
      - ./modelstore:/home/model-server/model-store
      - ./config:/home/model-server/config
    command: torchserve --start --ncs --model-store /home/model-server/model-store --ts-config /home/model-server/config/config.ts.properties
    environment:
      - METRICS_URL=http://prometheus:9090
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config/:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
  