name: Deploy TorchServe on GKE

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Google Cloud
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Install Pulumi
      uses: pulumi/actions@v2
      with:
        command: up
        stack_name: production  # Adjust as needed
        work_dir: pulumi  # Adjust if your Pulumi script is in a different directory
        comment_on_pr: true
        refresh: true
        secrets_provider: gcpkms://projects/your-project/locations/global/keyRings/your-keyring/cryptoKeys/your-key

    - name: Setup Kubectl
      run: |
        echo "${{ steps.deploy.outputs.kubeconfig }}" | base64 -d > kubeconfig
        echo "::set-env name=KUBECONFIG::$PWD/kubeconfig"

    - name: Deploy TorchServe using Kompose
      run: |
        sudo apt update && sudo apt install -y kompose
        kompose convert -f docker-compose.yml
        kubectl apply -f torchserve-deployment.yaml -f torchserve-service.yaml
