apiVersion: v1
kind: Service
metadata:
  name: yolonas-ts-service
spec:
  selector:
    app: yolonas-ts-deploy  # This should match the label that your deployment uses
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 8080  # Internal port (the port your pod is running on)
    - name: management
      port: 81
      targetPort: 81
    - name: grafana
      port: 3000
      targetPort: 3000
    selector:
      app: app-label
    type: LoadBalancer
  type: LoadBalancer