apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f dockercompose.ts-ezout.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: torchserve
  name: torchserve
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: torchserve
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f dockercompose.ts-ezout.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: torchserve
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      containers:
        - args:
            - torchserve
            - --start
            - --ncs
            - --model-store
            - /home/model-server/model-store
            - --ts-config
            - config/config.ts.properties
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
          image: us-docker.pkg.dev/ezout-vision-402700/ezout-vision/ezout-vision/yolonas-ts-deploy
          name: ezout-vision-ts
          resources: 
            limits:
              nvidia.com/gpu: "2"
            requests:
              cpu: "4"
              memory: "4Gi"
      restartPolicy: Always
status: {}